# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.23'

    - name: Install LLVM
      run: |
        # Add LLVM APT repository
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt-get update
        sudo apt-get install -y llvm-18-dev libllvm18 clang-18
        # Create symlinks for default tools
        sudo ln -sf /usr/bin/llvm-config-18 /usr/bin/llvm-config
        sudo ln -sf /usr/bin/clang-18 /usr/bin/clang

    - name: Build
      run: go build -tags llvm18 -v ./...

    - name: Test
      run: go test -tags llvm18 -v ./...
